"""empty message

Revision ID: 4f439dd2d3a6
Revises: eeafb5751920
Create Date: 2020-02-19 16:45:54.748067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f439dd2d3a6'
down_revision = 'eeafb5751920'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('creation_date', sa.DateTime(), nullable=True))
    op.add_column('venues', sa.Column('creation_date', sa.DateTime(), nullable=True))
    
    op.execute('UPDATE artists SET creation_date = current_timestamp WHERE creation_date IS NULL;')
    op.execute('UPDATE venues SET creation_date = current_timestamp WHERE creation_date IS NULL;')

    op.alter_column('artists', 'creation_date', nullable=False)
    op.alter_column('venues', 'creation_date', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'creation_date')
    op.drop_column('artists', 'creation_date')
    # ### end Alembic commands ###
