"""empty message

Revision ID: 4f627d82acbc
Revises: 7a5d68a698d9
Create Date: 2020-02-11 01:57:21.419685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f627d82acbc'
down_revision = '7a5d68a698d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('start_time', sa.Date(), nullable=False))
    op.drop_column('Show', 'name')
    op.drop_column('Show', 'date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('date', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('Show', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('Show', 'start_time')
    # ### end Alembic commands ###
